

spring:
  datasource:
    username: "root"
    password: "qwerty"
    url: "jdbc:mysql://localhost:3306/train"
    driver-class: "com.mysql.jdbc.Driver"
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
